"""The data contract every other module codes against.

Two kinds of model live here, and the split matters:

*Result* models (``TriageResult``, ``CorrelationResult``) are what an agent
generates. They are passed to Strands as ``structured_output_model``, so every
field description is read by the model and functions as an instruction.

*Record* models (``TriagedReport``, ``CorrelationSummary``) are what the
pipeline assembles and persists. They carry the result fields plus everything
the code knows or computes for itself.

``TriagedReport.summary`` does double duty as the redacted form and the indexed
form, and that is deliberate. An earlier design had a separate ``redacted_text``
holding a fuller rewrite; measurement killed it. Indexing the fuller text put
the weakest cluster report *below* an unrelated one (separation -0.03 to -0.16
across every query strategy tried), because incidental narration dominates the
embedding of a short text. Indexing the normalised sentence separates the same
groups by +0.28 to +0.52. Two model-written text fields would also have meant
two redaction surfaces to defend; there is now one.

Nothing a model could get wrong and nothing that must be trustworthy is left
to the model. Identifiers are derived deterministically; the numbers that feed
the escalation decision are counted from storage. ``distinct_reporters`` in
particular is a safety control (see IMPLEMENTATION_PLAN.md §4.2), and a
model-reported safety control is not a control.
"""

from __future__ import annotations

import hashlib
from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

ReportType = Literal["theft", "suspicious", "vandalism", "hazard", "other"]
Action = Literal["silent_log", "alert"]
Urgency = Literal["low", "medium", "high"]
# Decided 2026-08-21: alerts broadcast to the residents of the affected zone.
# Single-valued deliberately — the escalation agent does not choose a recipient,
# so an alert cannot be quietly narrowed or widened by a model. Widening the
# blast radius should be a code change someone reviews, not a token it emits.
Audience = Literal["zone_residents"]


def make_report_id(zone: str, timestamp: datetime, reporter_id: str, text: str) -> str:
    """Derive a stable 12-char id from a report's content.

    Deterministic on purpose. The demo renderer seeds each node's position from
    this value, so a given seed set always draws the same picture — you can
    re-shoot a take in week six without the graph moving. It also makes
    re-ingesting the same report idempotent rather than duplicating it.
    """
    digest = hashlib.sha256(
        "\x1f".join([zone, timestamp.isoformat(), reporter_id, text]).encode("utf-8")
    )
    return digest.hexdigest()[:12]


class RawReport(BaseModel):
    """A report exactly as it arrived, before any processing."""

    text: str = Field(description="The reporter's own words, unmodified.")
    zone: str = Field(
        description="Coarse area label, e.g. 'Elm St north' or 'Parcel lockers, bldg 3'. "
        "Never a street address — see PROJECT_BRIEF.md §6."
    )
    timestamp: datetime = Field(description="When the report was submitted.")
    reporter_id: str = Field(
        description="Opaque, stable per reporter. Used only to count distinct "
        "reporters in a cluster; never shown in an alert."
    )

    @property
    def report_id(self) -> str:
        return make_report_id(self.zone, self.timestamp, self.reporter_id, self.text)


class TriageResult(BaseModel):
    """What the triage agent produces. Generated by the model.

    Every field description below is part of the prompt.
    """

    report_type: ReportType = Field(
        description="The single category that best fits what is being reported."
    )
    severity: int = Field(
        ge=1,
        le=5,
        description=(
            "How serious this report is on its own, ignoring any other report. "
            "1 = trivial or ambiguous. 3 = a real but ordinary problem. "
            "5 = someone is in danger or a serious crime is in progress. "
            "Most reports are 1-2; reserve 4-5 for genuine emergencies."
        ),
    )
    summary: str = Field(
        description=(
            "One neutral sentence describing what happened, with every detail "
            "that could identify a PERSON removed and every detail about PLACE "
            "and BEHAVIOUR kept.\n\n"
            "REMOVE: names; physical descriptions (race, skin tone, height, "
            "build, hair, age, clothing); vehicle make, colour, or plate; house "
            "numbers and street addresses. Also drop incidental narration — "
            "'when I got back from work', 'probably nothing', 'again tonight'.\n\n"
            "KEEP, and be specific about: exactly what was involved and where. "
            "Write 'near the building's parcel lockers', not 'in the "
            "neighbourhood'. Write 'a vehicle has stayed parked in the same "
            "street position', not 'a parking issue'. Two reports about "
            "genuinely different things must not come out sounding the same — "
            "this sentence is what gets searched, so a vague one makes unrelated "
            "reports look related.\n\n"
            "Rewrite rather than blank out: 'a person was seen near the "
            "mailboxes', not '[REDACTED] was seen near the mailboxes'. Do not "
            "speculate about intent, and do not add judgement the reporter did "
            "not express.\n\n"
            "This sentence is the ONLY version of the report that is stored "
            "long-term, indexed, searched, and shown to a neighbour."
        )
    )


class TriagedReport(BaseModel):
    """A triaged report as persisted. Result fields plus what the code knows."""

    report_id: str
    zone: str
    timestamp: datetime
    reporter_id: str
    report_type: ReportType
    severity: int = Field(ge=1, le=5)
    summary: str

    @classmethod
    def from_raw(cls, raw: RawReport, result: TriageResult) -> TriagedReport:
        return cls(
            report_id=raw.report_id,
            zone=raw.zone,
            timestamp=raw.timestamp,
            reporter_id=raw.reporter_id,
            **result.model_dump(),
        )


class CorrelationResult(BaseModel):
    """What the correlation agent produces. Generated by the model.

    The agent decides *which* reports are related and says *why*. It does not
    report counts — the pipeline counts them from the ids below, so the evidence
    reaching the escalation agent is measured rather than asserted.
    """

    related_report_ids: list[str] = Field(
        default_factory=list,
        description=(
            "Ids of previously-logged reports that describe the same ongoing "
            "situation as the one being processed. Include a report only if you "
            "believe it is the SAME situation, not merely the same category — two "
            "unrelated bike thefts a month apart are not related. Empty list is the "
            "normal and expected answer."
        ),
    )
    assessment: str = Field(
        description=(
            "Your own reading of the evidence, in two or three sentences. Say what "
            "you searched for, what you found, and whether it looks like one "
            "situation or several unconnected ones. Include what argues AGAINST a "
            "pattern, not only what argues for one."
        )
    )


class CorrelationSummary(BaseModel):
    """Correlation evidence as assembled by the pipeline.

    Everything except ``assessment`` is computed from storage. This object is
    what the escalation agent weighs, so it has to be true.
    """

    cluster_size: int = Field(
        description="Reports in this cluster, including the one being processed."
    )
    distinct_reporters: int = Field(
        description=(
            "How many different people filed those reports. A cluster where this "
            "is 1 is one person's repeated concern, not a neighborhood pattern."
        )
    )
    time_span_hours: float = Field(
        description="Hours between the earliest and latest report in the cluster."
    )
    zones_involved: list[str] = Field(
        description="Distinct zones the cluster touches. More zones over more time "
        "means less likely to be one situation."
    )
    anomaly_score: float = Field(
        description="Z-score of this zone's current report rate against its own "
        "baseline. Not against other zones — a busy street is not an anomaly."
    )
    related_report_ids: list[str]
    assessment: str


class EscalationDecision(BaseModel):
    """The escalation agent's judgment. Generated by the model.

    ``reasoning`` is required and is shown on screen during the demo. It is the
    difference between an agent and a cron job.
    """

    action: Action = Field(
        description=(
            "'alert' only when the evidence shows a real, current pattern a person "
            "should act on. 'silent_log' for everything else, including cases that "
            "look similar but are too thin, too old, too scattered, or come from a "
            "single reporter. Declining is the normal outcome and is not a failure."
        )
    )
    urgency: Urgency = Field(
        description="How soon a human should look. Ignored when action is 'silent_log'."
    )
    audience: Audience = Field(
        default="zone_residents",
        description="Always 'zone_residents'. Alerts go to the residents of the "
        "zone the pattern is in; this is not a choice you make. Ignored when "
        "action is 'silent_log'."
    )
    message: str = Field(
        description=(
            "The alert a neighbor will read, in plain language, two or three "
            "sentences.\n\n"
            "Describe a PLACE TO WATCH, never a PERSON TO LOOK FOR. Do not include "
            "any physical description, name, or vehicle detail, even if one somehow "
            "appears in the evidence. Say what has been happening, where, and over "
            "what period, and what would be a reasonable thing to do about it.\n\n"
            "Empty string when action is 'silent_log'."
        )
    )
    reasoning: str = Field(
        description=(
            "Why you decided this, referring to the specific evidence — cluster "
            "size, distinct reporters, time span, zone spread, anomaly score. If "
            "you are declining, say which piece of evidence was decisive. Write it "
            "for a neighbor reading over your shoulder, not for a log file."
        )
    )


# One definition of what happened to a report, shared by every surface that
# counts them.
#
# This used to be written twice: pipeline.Processed.outcome bucketed by the
# live objects, and render.build_html re-derived its own buckets from stored
# rows with a different rule (`action != "alert" and cluster_size > 1`). That
# put a suppressed duplicate in "suppressed" in the terminal and in "declined"
# on the page, so the same run printed two different tallies — on camera,
# forty seconds apart, in VIDEO_SCRIPT §4. storage.rendered_rows() already
# promised in its docstring that the two "cannot disagree"; nothing enforced
# it. tests/test_pipeline.py::test_page_tally_matches_outcomes now does.
def outcome_of(
    *, action: str, sent: bool, suppressed: bool, cluster_size: int
) -> str:
    """One of: alert, suppressed, declined, silent.

    Order matters. A suppressed duplicate decided "alert" and is not a
    decline — the pipeline held it back because an alert already covers that
    cluster, which is a different fact about the system than the escalation
    agent choosing not to escalate.
    """
    if action == "alert" and sent:
        return "alert"
    if action == "alert" and suppressed:
        return "suppressed"
    if cluster_size > 1:
        return "declined"
    return "silent"
